INSERT INTO instytution(name, description) VALUES ('Dbam o Zdrowie', 'Pomoc dzieciom z ubogich rodzin.')
INSERT INTO instytution(name, description) VALUES ('A kogo', 'Pomoc wybudzaniu dzieci ze śpiączki.')
INSERT INTO instytution(name, description) VALUES ('Dla dzieci', 'Pomoc osobom znajdującym się w trudnej sytuacji życiowej.')
INSERT INTO instytution(name, description) VALUES ('Bez domu', 'Pomoc dla osób nie posiadających miejsca zamieszkania.')
INSERT INTO donation(quantity) VALUES (2)
INSERT INTO donation(quantity) VALUES (7)
INSERT INTO donation(quantity) VALUES (8)
INSERT INTO category(name) VALUES ('Ubrania, do wyrzucenia')
INSERT INTO category(name) VALUES ('Ubrania, które nadają sie do ponownego użycia')
INSERT INTO category(name) VALUES ('Zabawki')
INSERT INTO category(name) VALUES ('Książki')
INSERT INTO category(name) VALUES ('Inne')